<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <!-- Class library with no Razor files using ASP.NET Core APIs; see
         https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore (#264). -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dawn.Guard" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" />
    <None Include=".\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
