# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo "The branch name is ${{ github.repository }}"
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Ploch.Common.sln
      - name: Build
        run: dotnet build Ploch.Common.sln --no-restore
      - name: Test
        run: dotnet test Ploch.Common.sln --no-build --verbosity normal --logger "trx;LogFileName=TestOutputResults.xml"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/TestResults/*.xml
            **/TestResults/*.trx
      # - name: 'Qodana Scan'
      #   uses: JetBrains/qodana-action@main
      #   env:
      #     QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  