name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch output
        run: echo ::set-output name=branch::${{ github.repository }}
      - run: echo "The branch name is ${{ github.repository }}"
      - name: Test Report
        uses: dorny/test-reporter@v1
        id: test-report
        with:
          artifact: test-results
          name: 'Test Results'
          path: '**/TestResults/TestOutputResults.xml'
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read output variables
        run: |
          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
