name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: 'Test Results'
          path: '**/TestResults/TestOutputResults.xml'
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}
