name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: phoenix-actions/test-reporting@v8
      id: test-report                     # Set ID reference for step
      with:
        artifact: 'test-results'            # artifact name
        name: 'Test Results'
        path: '**/TestResults/TestOutputResults.xml'
        reporter: dotnet-trx
    - name: Read output variables
      run: |
        echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
